use ms_test;

INSERT INTO USERS (ID, NAME, PHONE, EMAIL, PWD, NICKNAME, CREATED_AT, UPDATED_AT)
VALUES ('test1', 'TestUser1', '010-1234-5678', 'testuser@example.com', '123', 'testNick', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO POSTS (TITLE, TEXT, CREATED_AT, UPDATED_AT, VIEW_COUNT, LIKE_COUNT, COMMENT_COUNT, CATEGORY, USER_ID)
VALUES ('Sample Title', 'This is a sample post content.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0, 0, 'General', 'test1');

INSERT INTO COMMENTS (POST_ID, TEXT, CREATED_AT, UPDATED_AT, USER_ID)
VALUES (1, 'This is a sample comment.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'test1');
