
BEGIN;

CREATE TABLE IF NOT EXISTS POSTS (
      ID INT AUTO_INCREMENT PRIMARY KEY,
      USERID VARCHAR(255) NOT NULL,
      TITLE VARCHAR(255) NOT NULL,
      NICKNAME VARCHAR(255),
      TEXTCONTENT TEXT,
      CATEGORY VARCHAR(255) NOT NULL,
      REFERENCEDID INT,
      CREATEDAT DATETIME,
      UPDATEDAT DATETIME,
      FOREIGN KEY (USERID) REFERENCES USERS(ID)
);

COMMIT;