use ms_test;

CREATE TABLE IF NOT EXISTS USERS (
	ID VARCHAR(255) PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    PWD VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS POSTS (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    TEXT TEXT NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    VIEW_COUNT INT DEFAULT 0,
    LIKE_COUNT INT DEFAULT 0,
    COMMENT_COUNT INT DEFAULT 0,
    CATEGORY VARCHAR(255) NOT NULL,
    REFERENCE_ID INT,
    USER_ID VARCHAR(255) NOT NULL,
    FOREIGN KEY (REFERENCE_ID) REFERENCES Posts(ID),
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);

CREATE TABLE IF NOT EXISTS COMMENTS (
    ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
    POST_ID INT NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    PARENT_ID LONG,
    USER_ID VARCHAR(255) NOT NULL,
    FOREIGN KEY (POST_ID) REFERENCES POSTS(ID),
    FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

show tables;
