
BEGIN;

CREATE TABLE IF NOT EXISTS POSTS (
      ID INT AUTO_INCREMENT PRIMARY KEY,
      USERID VARCHAR(255) NOT NULL,
      TITLE VARCHAR(255) NOT NULL,
      NICKNAME VARCHAR(255),
      TEXTCONTENT TEXT,
      CATEGORY VARCHAR(255) NOT NULL,
      REFERENCEDID INT,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
);

COMMIT;